server:
  port: 19002

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:18081/eureka/,http://localhost:18082/eureka/,http://localhost:18083/eureka/

spring:
  application:
    name: service-feign


feign:
  hystrix:
    enabled: true